name: ejects_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dropdown_button2: ^1.4.0
  pinput: ^2.2.6
  auto_size_text_field: ^1.0.1
  dotted_border: ^2.0.0
  image_picker: ^0.8.5
  flick_video_player: ^0.3.1
  video_player: ^2.4.4
  grouped_list: ^4.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icon/
    - assets/image/


  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 500


